# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuccessResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, message: str=None, data: object=None):  # noqa: E501
        """SuccessResponse - a model defined in Swagger

        :param type: The type of this SuccessResponse.  # noqa: E501
        :type type: str
        :param message: The message of this SuccessResponse.  # noqa: E501
        :type message: str
        :param data: The data of this SuccessResponse.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            'type': str,
            'message': str,
            'data': object
        }

        self.attribute_map = {
            'type': 'type',
            'message': 'message',
            'data': 'data'
        }

        self._type = type
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessResponse of this SuccessResponse.  # noqa: E501
        :rtype: SuccessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this SuccessResponse.


        :return: The type of this SuccessResponse.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this SuccessResponse.


        :param type: The type of this SuccessResponse.
        :type type: str
        """

        self._type = type

    @property
    def message(self) -> str:
        """Gets the message of this SuccessResponse.


        :return: The message of this SuccessResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this SuccessResponse.


        :param message: The message of this SuccessResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> object:
        """Gets the data of this SuccessResponse.


        :return: The data of this SuccessResponse.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this SuccessResponse.


        :param data: The data of this SuccessResponse.
        :type data: object
        """

        self._data = data
